export const config = {
    RPC_URL: 'https://rpc-terp.zenchainlabs.io',
    REST_URL: 'https://api-terp.zenchainlabs.io',
    EXPLORER_URL: 'https://explorer.nodestake.top/terp',
    STAKING_URL: 'https://stake.terp.network',
    NETWORK_NAME: 'Terp Network',
    NETWORK_TYPE: 'mainnet',
    CHAIN_ID: 'morocco-1',
    CHAIN_NAME: 'Terp-Network',
    GOV_COIN_DENOM: 'TERP',
    GOV_COIN_MINIMAL_DENOM: 'uterp',
    GAS_COIN_MINIMAL_DENOM: 'uthiol',
    COIN_DECIMALS: 6,
    GAS_COIN_DENOM: 'THIOL',
    FEE_CURRENCY: 'uthiol',
    PREFIX: 'terp',
    COIN_TYPE: 118,
    COINGECKO_ID: 'terp',
    GAS_PRICE_STEP_LOW: 0.001,
    GAS_PRICE_STEP_AVERAGE: 0.03,
    GAS_PRICE_STEP_HIGH: 0.06,
    FEATURES: ['ibc-transfer', 'ibc-go'],
};