export const config = {
    RPC_URL: 'https://rpc.nodestake.top/',
    REST_URL: 'https://api.nodestake.top/',
    EXPLORER_URL: 'https://www.skynetexplorers.com/terpnetwork/',
    STAKING_URL: 'https://stake.terp.network',
    NETWORK_NAME: 'Terp Network',
    NETWORK_TYPE: 'testnet',
    CHAIN_ID: 'morocco-1',
    CHAIN_NAME: 'Terp-Network',
    GOV_COIN_DENOM: 'TERP',
    GOV_COIN_MINIMAL_DENOM: 'uterp',
    COIN_DECIMALS: 6,
    GAS_COIN_DENOM: 'THIOL',
    COIN_MINIMAL_DENOM: 'uthiol',
    FEE_CURRENCY: 'uthiol',
    PREFIX: 'terp',
    COIN_TYPE: 118,
    GOV_COINGECKO_ID: 'terp',
    GAS_COINGECKO_ID: 'thiol',
    GAS_PRICE_STEP_LOW: 0.001,
    GAS_PRICE_STEP_AVERAGE: 0.03,
    GAS_PRICE_STEP_HIGH: 0.06,
    FEATURES: ['ibc-transfer', 'ibc-go', 'stargate'],
};
